languageCode = "en-us"
title = "HOT-PDC Training Site" #<-- change me
theme = "book"
DefaultContentLanguage = "id"
relativeurls = true
enableGitInfo = true

[params]
    BookRepo = "https://github.com/hotosm/pdc-documentation" #<-- change me
    BookShowToC = false
    BookEditPath = "/edit/master/content/"

[imaging]
    resampleFilter = "box"
    quality = 75